name: Ola Mundo
on: workflow_dispatch
jobs:
  Prazer:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: date
      - name: Dizer ola
        run: echo "Commit feito por ${{ github.actor }}"
