name: Ola Mundo
on: push
jobs:
  saudacao:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: date
      - name: Dizer ola
        run: echo "Ola, novamente, estou fazendo a segunda etapa do meu primeiro GitHub Action."
