name: Ola Mundo
on: push
jobs:
  saudacao:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: echo "Ola, mundo! Sou Juan Marcondes e esse é meu primeiro GitHub Action."
      - name: Dizer ola
        run: echo "Ola, novamente, estou fazendo a segunda etapa do meu primeiro GitHub Action."
